// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA1QFY0BnzeORuHK4gMSXA_NsL25D-_Od0',
    appId: '1:457795647842:web:55ddb294aab180caf5543b',
    messagingSenderId: '457795647842',
    projectId: 'deep-focus-29216',
    authDomain: 'deep-focus-29216.firebaseapp.com',
    storageBucket: 'deep-focus-29216.firebasestorage.app',
    measurementId: 'G-GY4HDEM0M7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCXEPyh7x0VOKHHo9QgM-rbzTXC7xj_ZUc',
    appId: '1:457795647842:android:47602948926bb619f5543b',
    messagingSenderId: '457795647842',
    projectId: 'deep-focus-29216',
    storageBucket: 'deep-focus-29216.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDtwCw-UDiYsEllQOlZqJOYOI5P5Qk7QHE',
    appId: '1:457795647842:ios:d4bd943656f1d5bef5543b',
    messagingSenderId: '457795647842',
    projectId: 'deep-focus-29216',
    storageBucket: 'deep-focus-29216.firebasestorage.app',
    iosBundleId: 'com.example.deepFocus',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDtwCw-UDiYsEllQOlZqJOYOI5P5Qk7QHE',
    appId: '1:457795647842:ios:d4bd943656f1d5bef5543b',
    messagingSenderId: '457795647842',
    projectId: 'deep-focus-29216',
    storageBucket: 'deep-focus-29216.firebasestorage.app',
    iosBundleId: 'com.example.deepFocus',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA1QFY0BnzeORuHK4gMSXA_NsL25D-_Od0',
    appId: '1:457795647842:web:ae2e61bf4b016f2ef5543b',
    messagingSenderId: '457795647842',
    projectId: 'deep-focus-29216',
    authDomain: 'deep-focus-29216.firebaseapp.com',
    storageBucket: 'deep-focus-29216.firebasestorage.app',
    measurementId: 'G-4XGN03CPEE',
  );
}
